version: '3.8'

services:
  identityservice:
    build:
      context: .
      dockerfile: SanboxServerManager.IdentityService/Dockerfile
    environment:
      - ConnectionStrings__IdentityContext=Host=identitydb;Database=Identitydb;Username=postgres;Password=131313
    ports:
      - 5155:80
    depends_on:
      - identitydb
      - rabbitmq
    networks:
      - snbx-network

  sanboxservermanager.webapi:
    build:
      context: .
      dockerfile: SanboxServerManager.WebApi/Dockerfile
    environment:
      - ConnectionStrings__SandboxServerContext=Host=snbxdb;Database=SandboxServerDb;Username=postgres;Password=131313
    ports:
      - 5154:80
    depends_on:
      - snbxdb
      - rabbitmq
    networks:
      - snbx-network

  snbxdb:
    image: postgres
    container_name: snbxdb
    environment:
      - POSTGRES_DB=SandboxServerDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=131313
    ports:
      - 5432:5432
    networks:
      - snbx-network

  consolemessageservice:
    build:
      context: .
      dockerfile: SanboxServerManager.ConsoleMessageService/Dockerfile
    depends_on:
      - rabbitmq
    networks: 
    - snbx-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: 
    - snbx-network

  identitydb:
    image: postgres
    container_name: identitydb
    environment:
      - POSTGRES_DB=Identitydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=131313
    ports:
      - 5433:5432

    networks:
      - snbx-network

networks:
  snbx-network:
    driver: bridge
